# Generated by Django 5.1 on 2024-08-18 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_requestcounter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestcounter',
            name='count',
            field=models.DecimalField(decimal_places=1, max_digits=15),
        ),
    ]
